export const createJobSchema = {
    title: { type: 'string', example: 'Emmanuel', required: true },
    department: { type: 'string', example: 'BE0704651352', required: true },
    employmentRatio: { type: 'string', example: 'Niels', required: false },
    maxAmountOfApplicants: { type: 'number', example: 10, required: false },
    contractTerm: { type: 'array' },
    salaryPackage: { type: 'string', example: '9090909090', required: false },
    experience: { type: 'string', example: '12443344334', required: false },
    responsible: { type: 'string', example: 'Jacobs', required: false },
    address: { type: 'string', example: '44-65 Laparella Cinco, Donella, Mexico City, Mexico' },
    description: { type: 'string', example: 'A versatile back-end node.js developer' },
    applicantForm: { type: 'string', example: 'A versatile back-end node.js developer' },
    applicantProcess: { type: 'string', example: 'A versatile back-end node.js developer' },
    status: { type: 'nuber', example: 1 },
    organizationId: { type: 'string', example: '126373' },
}

export const updateJobSchema = {
    title: { type: 'string', example: 'Emmanuel', required: true },
    department: { type: 'string', example: 'BE0704651352', required: true },
    employmentRatio: { type: 'string', example: 'Niels', required: false },
    maxAmountOfApplicants: { type: 'number', example: 10, required: false },
    contractTerm: { type: 'string' },
    salaryPackage: { type: 'string', example: '9090909090', required: false },
    experience: { type: 'string', example: '12443344334', required: false },
    responsible: { type: 'string', example: 'Jacobs', required: false },
    address: { type: 'string', example: '44-65 Laparella Cinco, Donella, Mexico City, Mexico' },
    description: { type: 'string', example: 'A versatile back-end node.js developer' },
    applicantForm: { type: 'string', example: 'A versatile back-end node.js developer' },
    applicantProcess: { type: 'string', example: 'A versatile back-end node.js developer' },
    organizationId: { type: 'string', example: '126373' },
    status: { type: 'number', example: 1 },
}

export const requestJobValidationSchema = {
    type: 'object',
    properties: {
        _id: { type: 'string' },
        id: { type: 'string' },
        title: { type: 'string', minLength: 2, maxLength: 80 },
        department: { type: 'string' },
        employmentRatio: { type: 'string' },
        organizationId: { type: 'string' },
        maxAmountOfApplicants: { type: 'number' },
        contractTerm: { type: 'string' },
        salaryPackage: { type: 'string' },
        experience: { type: 'string' },
        responsible: { type: 'string' },
        address: { type: 'string' },
        description: { type: 'string' },
        applicantForm: { type: 'string' },
        applicantProcess: { type: 'string' },
        status: { type: 'number' },

        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
    },
    additionalProperties: false,
}
